In [ ]:
# 1. Uninstall the conflicting audio library that we don't need
!pip uninstall -y torchaudio

# 2. Cleanly install the modern Hugging Face ecosystem
!pip install -U bitsandbytes transformers datasets accelerate trl

# 3. Automatically restart the python interpreter to apply changes safely
import os
os.kill(os.getpid(), 9)

Found existing installation: torchaudio 2.11.0+cu128
Uninstalling torchaudio-2.11.0+cu128:
  Successfully uninstalled torchaudio-2.11.0+cu128
Collecting bitsandbytes
  Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.12.1)
Collecting transformers
  Downloading transformers-5.14.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Collecting datasets
  Downloading datasets-5.0.0-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.14.0)
Collecting trl
  Downloading trl-1.8.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.11.0+cu128)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (26.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.20.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.4)
Collecting pyarrow>=21.0.0 (from datasets)
  Downloading pyarrow-25.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.7.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from trl) (3.1.6)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.14.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.6.1)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->trl) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch<3,>=2.3->bitsandbytes) (1.5.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl (60.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 15.4 MB/s eta 0:00:00
Downloading transformers-5.14.0-py3-none-any.whl (11.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 71.1 MB/s eta 0:00:00
Downloading datasets-5.0.0-py3-none-any.whl (555 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 555.1/555.1 kB 35.4 MB/s eta 0:00:00
Downloading trl-1.8.0-py3-none-any.whl (863 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 863.2/863.2 kB 51.9 MB/s eta 0:00:00
Downloading pyarrow-25.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (50.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 12.4 MB/s eta 0:00:00
Installing collected packages: pyarrow, datasets, bitsandbytes, transformers, trl
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
  Attempting uninstall: transformers
    Found existing installation: transformers 5.12.1
    Uninstalling transformers-5.12.1:
      Successfully uninstalled transformers-5.12.1
Successfully installed bitsandbytes-0.49.2 datasets-5.0.0 pyarrow-25.0.0 transformers-5.14.0 trl-1.8.0

In [ ]:
!pip install -q -U bitsandbytes datasets transformers peft trl accelerate

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 20.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 555.1/555.1 kB 41.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.5/11.5 MB 124.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 863.2/863.2 kB 56.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 15.8 MB/s eta 0:00:00

In [ ]:
import torch
import torch.nn as nn
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from datasets import load_dataset
from trl import SFTTrainer, SFTConfig
from peft import LoraConfig, get_peft_model

# ==========================================
# 1. SETUP MODEL AND DATASET
# ==========================================
model_id = "Qwen/Qwen2.5-1.5B-Instruct"
print(f"Loading base model: {model_id}...")

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token

# Load clean copy of base model
base_model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto"
)

# Load configuration matching the schema
print("Fetching dataset...")
raw_dataset = load_dataset("lavita/medical-qa-datasets", "chatdoctor-icliniq", split="test[:1000]")

# Dynamically intercept internal schema keys ('input' and 'output')
sample = raw_dataset[0]
q_key = 'question' if 'question' in sample else ('input' if 'input' in sample else list(sample.keys())[0])
a_key = 'answer_text' if 'answer_text' in sample else ('output' if 'output' in sample else list(sample.keys())[1])

def format_prompts(batch):
    formatted_texts = []
    for q, a in zip(batch[q_key], batch[a_key]):
        text = f"<|im_start|>user\nContext: You are a medical expert assistant. Answer this query: {q}<|im_end|>\n<|im_start|>assistant\n{a}<|im_end|>"
        formatted_texts.append(text)
    return {"text": formatted_texts}

dataset = raw_dataset.map(format_prompts, batched=True)
print("Dataset loaded and formatted successfully!")

# ==========================================
# 2. RUN EXPERIMENT 1: STANDARD LORA
# ==========================================
print("\n--- Initializing Run 1: Standard LoRA ---")

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

lora_model = get_peft_model(base_model, lora_config)

# Using SFTConfig with modern 'max_length' parameter naming
training_args_lora = SFTConfig(
    output_dir="./results_lora",
    dataset_text_field="text",
    max_length=512,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    max_steps=50,
    learning_rate=2e-4,
    fp16=False,
    bf16=True,
    logging_steps=10,
    save_strategy="no",
    report_to="none"
)

trainer_lora = SFTTrainer(
    model=lora_model,
    train_dataset=dataset,
    args=training_args_lora
)

trainer_lora.train()
lora_model.save_pretrained("./medical_lora_adapter")
print("Standard LoRA trained and saved successfully.")

# ==========================================
# 3. RUN EXPERIMENT 2: BRAIN-INSPIRED MTLoRA
# ==========================================
print("\n--- Initializing Run 2: Brain-Inspired MTLoRA ---")

# Define structural linear transformation overlay mimicking synaptic transformation matrices
class MTLoRATransformationWrapper(nn.Module):
    def __init__(self, base_layer, rank=16):
        super().__init__()
        self.base_layer = base_layer
        # Brain-inspired scaling and rotation matrix overlay
        self.transform_matrix = nn.Parameter(torch.eye(rank, dtype=torch.bfloat16))

    def forward(self, x, *args, **kwargs):
        if hasattr(self.base_layer, 'lora_A') and 'default' in self.base_layer.lora_A:
            original_lora_A = self.base_layer.lora_A['default']
            self.base_layer.lora_A['default'].weight.data = torch.matmul(
                self.transform_matrix, original_lora_A.weight.data
            )
        return self.base_layer(x, *args, **kwargs)

# Reset model state back to baseline for an identical starting point
mtlora_model = get_peft_model(base_model, lora_config)

# Inject transformation layers into target query vectors
for name, module in mtlora_model.named_modules():
    if "q_proj" in name and hasattr(module, 'base_layer'):
        parent_name = name.rsplit('.', 1)[0]
        child_name = name.rsplit('.', 1)[-1]
        parent_module = mtlora_model.get_submodule(parent_name)
        setattr(parent_module, child_name, MTLoRATransformationWrapper(module, rank=16))

# Apply matching SFTConfig layout
training_args_mtlora = SFTConfig(
    output_dir="./results_mtlora",
    dataset_text_field="text",
    max_length=512,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    max_steps=50,
    learning_rate=2e-4,
    fp16=False,
    bf16=True,
    logging_steps=10,
    save_strategy="no",
    report_to="none"
)

trainer_mtlora = SFTTrainer(
    model=mtlora_model,
    train_dataset=dataset,
    args=training_args_mtlora
)

trainer_mtlora.train()
mtlora_model.save_pretrained("./medical_mtlora_adapter")
print("MTLoRA Adapter trained and saved successfully.")

Loading base model: Qwen/Qwen2.5-1.5B-Instruct...

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

Fetching dataset...
Dataset loaded and formatted successfully!

--- Initializing Run 1: Standard LoRA ---

Adding EOS to train dataset:   0%|          | 0/1000 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/1000 [00:00<?, ? examples/s]

Building labels for train dataset:   0%|          | 0/1000 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/1000 [00:00<?, ? examples/s]

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

Standard LoRA trained and saved successfully.

--- Initializing Run 2: Brain-Inspired MTLoRA ---

/usr/local/lib/python3.12/dist-packages/peft/mapping_func.py:72: UserWarning: You are trying to modify a model with PEFT for a second time. If you want to reload the model with a different config, make sure to call `.unload()` before.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:302: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

MTLoRA Adapter trained and saved successfully.

In [ ]:
import os
from google.colab import files

# 1. Zip both adapter directories into a single transportable archive
print("Packaging adapters...")
!zip -r medical_adapters.zip ./medical_lora_adapter ./medical_mtlora_adapter

# 2. Trigger the browser download download hook
print("Downloading file to your local computer...")
files.download('medical_adapters.zip')
print("Download request sent! Keep this zip file handy for your Raspberry Pi.")

Packaging adapters...
  adding: medical_lora_adapter/ (stored 0%)
  adding: medical_lora_adapter/README.md (deflated 65%)
  adding: medical_lora_adapter/adapter_model.safetensors (deflated 22%)
  adding: medical_lora_adapter/adapter_config.json (deflated 58%)
  adding: medical_mtlora_adapter/ (stored 0%)
  adding: medical_mtlora_adapter/README.md (deflated 65%)
  adding: medical_mtlora_adapter/adapter_model.safetensors (deflated 22%)
  adding: medical_mtlora_adapter/adapter_config.json (deflated 58%)
Downloading file to your local computer...

Download request sent! Keep this zip file handy for your Raspberry Pi.

In [ ]:
# Clone the official llama.cpp repository for conversion tools
!git clone https://github.com/ggerganov/llama.cpp
%cd llama.cpp

# Install the Python dependencies needed for the conversion scripts
!pip install -r requirements.txt
%cd ..

fatal: destination path 'llama.cpp' already exists and is not an empty directory.
/content/llama.cpp
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cpu, https://download.pytorch.org/whl/nightly, https://download.pytorch.org/whl/cpu, https://download.pytorch.org/whl/nightly, https://download.pytorch.org/whl/cpu, https://download.pytorch.org/whl/nightly
Ignoring torch: markers 'platform_machine == "s390x"' don't match your environment
Ignoring torch: markers 'platform_machine == "s390x"' don't match your environment
Requirement already satisfied: numpy~=1.26.4 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-convert_legacy_llama.txt (line 1)) (1.26.4)
Requirement already satisfied: sentencepiece<0.3.0,>=0.1.98 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-convert_legacy_llama.txt (line 2)) (0.2.1)
Requirement already satisfied: transformers==4.57.6 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-convert_legacy_llama.txt (line 4)) (4.57.6)
Requirement already satisfied: gguf>=0.1.0 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-convert_legacy_llama.txt (line 6)) (0.19.0)
Requirement already satisfied: protobuf<5.0.0,>=4.21.0 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-convert_legacy_llama.txt (line 7)) (4.25.9)
Requirement already satisfied: torch==2.11.0 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (2.11.0+cu128)
Requirement already satisfied: aiohttp~=3.9.3 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-tool_bench.txt (line 1)) (3.9.5)
Requirement already satisfied: pytest~=8.3.3 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-tool_bench.txt (line 2)) (8.3.5)
Requirement already satisfied: matplotlib~=3.10.0 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-tool_bench.txt (line 3)) (3.10.0)
Requirement already satisfied: openai~=2.14.0 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-tool_bench.txt (line 5)) (2.14.0)
Requirement already satisfied: pandas~=2.2.3 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-tool_bench.txt (line 6)) (2.2.3)
Requirement already satisfied: prometheus-client~=0.20.0 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-tool_bench.txt (line 7)) (0.20.0)
Requirement already satisfied: requests~=2.32.3 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-tool_bench.txt (line 8)) (2.32.4)
Requirement already satisfied: wget~=3.2 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-tool_bench.txt (line 9)) (3.2)
Requirement already satisfied: typer~=0.24.1 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-tool_bench.txt (line 10)) (0.24.2)
Requirement already satisfied: seaborn~=0.13.2 in /usr/local/lib/python3.12/dist-packages (from -r ./requirements/requirements-tool_bench.txt (line 11)) (0.13.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.6->-r ./requirements/requirements-convert_legacy_llama.txt (line 4)) (3.29.4)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.6->-r ./requirements/requirements-convert_legacy_llama.txt (line 4)) (0.36.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.6->-r ./requirements/requirements-convert_legacy_llama.txt (line 4)) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.6->-r ./requirements/requirements-convert_legacy_llama.txt (line 4)) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.6->-r ./requirements/requirements-convert_legacy_llama.txt (line 4)) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.6->-r ./requirements/requirements-convert_legacy_llama.txt (line 4)) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.6->-r ./requirements/requirements-convert_legacy_llama.txt (line 4)) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.6->-r ./requirements/requirements-convert_legacy_llama.txt (line 4)) (4.67.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (4.15.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (12.8.90)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.12/dist-packages (from aiohttp~=3.9.3->-r ./requirements/requirements-tool_bench.txt (line 1)) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp~=3.9.3->-r ./requirements/requirements-tool_bench.txt (line 1)) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp~=3.9.3->-r ./requirements/requirements-tool_bench.txt (line 1)) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp~=3.9.3->-r ./requirements/requirements-tool_bench.txt (line 1)) (6.7.1)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp~=3.9.3->-r ./requirements/requirements-tool_bench.txt (line 1)) (1.24.2)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.12/dist-packages (from pytest~=8.3.3->-r ./requirements/requirements-tool_bench.txt (line 2)) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.12/dist-packages (from pytest~=8.3.3->-r ./requirements/requirements-tool_bench.txt (line 2)) (1.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib~=3.10.0->-r ./requirements/requirements-tool_bench.txt (line 3)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib~=3.10.0->-r ./requirements/requirements-tool_bench.txt (line 3)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib~=3.10.0->-r ./requirements/requirements-tool_bench.txt (line 3)) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib~=3.10.0->-r ./requirements/requirements-tool_bench.txt (line 3)) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib~=3.10.0->-r ./requirements/requirements-tool_bench.txt (line 3)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib~=3.10.0->-r ./requirements/requirements-tool_bench.txt (line 3)) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib~=3.10.0->-r ./requirements/requirements-tool_bench.txt (line 3)) (2.9.0.post0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai~=2.14.0->-r ./requirements/requirements-tool_bench.txt (line 5)) (4.14.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai~=2.14.0->-r ./requirements/requirements-tool_bench.txt (line 5)) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai~=2.14.0->-r ./requirements/requirements-tool_bench.txt (line 5)) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai~=2.14.0->-r ./requirements/requirements-tool_bench.txt (line 5)) (0.15.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai~=2.14.0->-r ./requirements/requirements-tool_bench.txt (line 5)) (2.13.4)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai~=2.14.0->-r ./requirements/requirements-tool_bench.txt (line 5)) (1.3.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas~=2.2.3->-r ./requirements/requirements-tool_bench.txt (line 6)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas~=2.2.3->-r ./requirements/requirements-tool_bench.txt (line 6)) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests~=2.32.3->-r ./requirements/requirements-tool_bench.txt (line 8)) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests~=2.32.3->-r ./requirements/requirements-tool_bench.txt (line 8)) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests~=2.32.3->-r ./requirements/requirements-tool_bench.txt (line 8)) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests~=2.32.3->-r ./requirements/requirements-tool_bench.txt (line 8)) (2026.6.17)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer~=0.24.1->-r ./requirements/requirements-tool_bench.txt (line 10)) (8.4.2)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer~=0.24.1->-r ./requirements/requirements-tool_bench.txt (line 10)) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer~=0.24.1->-r ./requirements/requirements-tool_bench.txt (line 10)) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer~=0.24.1->-r ./requirements/requirements-tool_bench.txt (line 10)) (0.0.4)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (1.5.5)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai~=2.14.0->-r ./requirements/requirements-tool_bench.txt (line 5)) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai~=2.14.0->-r ./requirements/requirements-tool_bench.txt (line 5)) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.57.6->-r ./requirements/requirements-convert_legacy_llama.txt (line 4)) (1.5.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai~=2.14.0->-r ./requirements/requirements-tool_bench.txt (line 5)) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai~=2.14.0->-r ./requirements/requirements-tool_bench.txt (line 5)) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai~=2.14.0->-r ./requirements/requirements-tool_bench.txt (line 5)) (0.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib~=3.10.0->-r ./requirements/requirements-tool_bench.txt (line 3)) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer~=0.24.1->-r ./requirements/requirements-tool_bench.txt (line 10)) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer~=0.24.1->-r ./requirements/requirements-tool_bench.txt (line 10)) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (1.3.0)
Requirement already satisfied: propcache>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from yarl<2.0,>=1.0->aiohttp~=3.9.3->-r ./requirements/requirements-tool_bench.txt (line 1)) (0.5.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch==2.11.0->-r ./requirements/requirements-convert_hf_to_gguf.txt (line 5)) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer~=0.24.1->-r ./requirements/requirements-tool_bench.txt (line 10)) (0.1.2)
/content

In [ ]:
!pip install -U torchao>=0.16.0
import os
os.kill(os.getpid(), 9)

In [ ]:
import os
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

model_id = "Qwen/Qwen2.5-1.5B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_id)

# Helper function to load, merge, and export to unquantized FP16 directory
def merge_and_export(adapter_path, output_dir):
    print(f"Merging {adapter_path} with base model...")
    # Load base model in FP16 for clean merging
    base = AutoModelForCausalLM.from_pretrained(
        model_id,
        torch_dtype=torch.float16,
        device_map="cpu"
    )
    # Load the adapter layers
    model = PeftModel.from_pretrained(base, adapter_path)
    # Seamlessly fuse the weights back together permanently
    merged_model = model.merge_and_unload()

    # Save the full model locally
    merged_model.save_pretrained(output_dir)
    tokenizer.save_pretrained(output_dir)
    print(f"Saved merged model to {output_dir}\n")

# 1. Merge the Standard LoRA
merge_and_export("./medical_lora_adapter", "./merged_lora")

# 2. Merge the custom MTLoRA
merge_and_export("./medical_mtlora_adapter", "./merged_mtlora")

# ========================================================
# 3. CONVERT TO GGUF AND QUANTIZE (Using llama.cpp tools)
# ========================================================
print("Converting merged models to base GGUF format...")

# Convert directories to FP16 .gguf files
!python llama.cpp/convert_hf_to_gguf.py ./merged_lora --outfile ./lora_fp16.gguf
!python llama.cpp/convert_hf_to_gguf.py ./merged_mtlora --outfile ./mtlora_fp16.gguf

print("\nQuantizing models to 4-bit (Q4_K_M) for optimal Pi performance...")

# Compile the llama-quantize binary tool quickly
!make -C llama.cpp llama-quantize

# Quantize both models to lightweight versions
!./llama.cpp/llama-quantize ./lora_fp16.gguf ./medical_lora_q4.gguf Q4_K_M
!./llama.cpp/llama-quantize ./mtlora_fp16.gguf ./medical_mtlora_q4.gguf Q4_K_M

print("\nSuccess! Both models are converted to quantized GGUF format.")

WARNING:torchao:Failed to load /usr/local/lib/python3.12/dist-packages/torchao/_C_cutlass_90a.abi3.so: Could not load this library: /usr/local/lib/python3.12/dist-packages/torchao/_C_cutlass_90a.abi3.so
WARNING:torchao:Failed to load /usr/local/lib/python3.12/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so: Could not load this library: /usr/local/lib/python3.12/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/660 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

Merging ./medical_lora_adapter with base model...

model.safetensors:   0%|          | 0.00/3.09G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

ValueError: Can't find 'adapter_config.json' at './medical_lora_adapter'

In [ ]:
# Force install the specific Protobuf version that TensorFlow 2.20 expects
!pip install -U "protobuf>=5.28.0" "torchao>=0.16.0"

# Kill the runtime to force a clean memory reload
import os
os.kill(os.getpid(), 9)

Collecting protobuf>=5.28.0
  Downloading protobuf-7.35.1-cp310-abi3-manylinux2014_x86_64.whl.metadata (595 bytes)
Collecting torchao>=0.16.0
  Downloading torchao-0.17.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (20 kB)
Downloading protobuf-7.35.1-cp310-abi3-manylinux2014_x86_64.whl (327 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 327.1/327.1 kB 12.4 MB/s eta 0:00:00
Downloading torchao-0.17.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 84.8 MB/s eta 0:00:00
Installing collected packages: torchao, protobuf
  Attempting uninstall: torchao
    Found existing installation: torchao 0.10.0
    Uninstalling torchao-0.10.0:
      Successfully uninstalled torchao-0.10.0
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.25.9
    Uninstalling protobuf-4.25.9:
      Successfully uninstalled protobuf-4.25.9
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-ai-generativelanguage 0.6.15 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 7.35.1 which is incompatible.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 7.35.1 which is incompatible.
ydf 0.15.0 requires protobuf<7.0.0,>=5.29.1, but you have protobuf 7.35.1 which is incompatible.
Successfully installed protobuf-7.35.1 torchao-0.17.0

In [ ]:
# ========================================================
# 1. SETUP ENGINE & DEPENDENCIES VIA CMAKE
# ========================================================
print("Setting up llama.cpp tools...")
!rm -rf llama.cpp
!git clone https://github.com/ggerganov/llama.cpp

# Install ONLY the light conversion requirements needed for the script
!pip install -r llama.cpp/requirements/requirements-convert-hf-to-gguf.txt

# Compile using CMake instead of Makefile
print("\nBuilding llama.cpp via CMake...")
!mkdir -p llama.cpp/build
%cd llama.cpp/build
!cmake .. -DLLAMA_GGML_BACKEND=CPU
!cmake --build . --config Release --target llama-quantize
%cd ../..

print("\nExtracting uploaded adapters...")
!unzip -o medical_adapters.zip

# Create paths for the model layers
import os
os.makedirs("./merged_lora", exist_ok=True)
os.makedirs("./merged_mtlora", exist_ok=True)
!cp -r ./medical_lora_adapter/* ./merged_lora/
!cp -r ./medical_mtlora_adapter/* ./merged_mtlora/

# ========================================================
# 2. CONVERT HF DIRECTORIES TO BASE GGUF
# ========================================================
print("\nConverting directories to GGUF format...")
# Pointing to the correct script location in the modern repo structure
!python llama.cpp/convert-hf-to-gguf.py ./merged_lora --outfile ./lora_fp16.gguf --outtype f16
!python llama.cpp/convert-hf-to-gguf.py ./merged_mtlora --outfile ./mtlora_fp16.gguf --outtype f16

# ========================================================
# 3. EXPORT TO 4-BIT QUANTIZATION
# ========================================================
print("\nQuantizing models to 4-bit (Q4_K_M) for Raspberry Pi...")
# Updated path pointing to the new CMake binary output location
!./llama.cpp/build/bin/llama-quantize ./lora_fp16.gguf ./medical_lora_q4.gguf Q4_K_M
!./llama.cpp/build/bin/llama-quantize ./mtlora_fp16.gguf ./medical_mtlora_q4.gguf Q4_K_M

# Verify files exist before running the download hook
if os.path.exists('medical_lora_q4.gguf') and os.path.exists('medical_mtlora_q4.gguf'):
    print("\nSuccess! Both models are successfully built into Q4_K_M GGUF format.")
    print("Initiating browser file downloads...")
    from google.colab import files
    files.download('medical_lora_q4.gguf')
    files.download('medical_mtlora_q4.gguf')
else:
    print("\n[ERROR]: GGUF files were not created. Check terminal output log traces above.")

Setting up llama.cpp tools...
Cloning into 'llama.cpp'...
remote: Enumerating objects: 103910, done.
remote: Counting objects: 100% (170/170), done.
remote: Compressing objects: 100% (135/135), done.
remote: Total 103910 (delta 80), reused 35 (delta 35), pack-reused 103740 (from 3)
Receiving objects: 100% (103910/103910), 409.46 MiB | 29.14 MiB/s, done.
Resolving deltas: 100% (72608/72608), done.
Updating files: 100% (3224/3224), done.
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'llama.cpp/requirements/requirements-convert-hf-to-gguf.txt'

Building llama.cpp via CMake...
/content/llama.cpp/build
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMAKE_BUILD_TYPE=Release
-- Found Git: /usr/bin/git (found version "2.34.1")
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Warning: ccache not found - consider installing it for faster compilation or disable this warning with GGML_CCACHE=OFF
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- GGML_SYSTEM_ARCH: x86
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Including CPU backend
-- x86 detected
-- Adding CPU backend variant ggml-cpu: -march=native
-- ggml version: 0.16.0
-- ggml commit:  505b1ed15
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "3.0.2")
-- Performing Test OPENSSL_VERSION_SUPPORTED
-- Performing Test OPENSSL_VERSION_SUPPORTED - Success
-- OpenSSL found: 3.0.2
-- Generating embedded license file for target: llama-app
-- Configuring done (1.7s)
-- Generating done (0.3s)
CMake Warning:
  Manually-specified variables were not used by the project:

    LLAMA_GGML_BACKEND


-- Build files have been written to: /content/llama.cpp/build
[  0%] Building CXX object vendor/cpp-httplib/CMakeFiles/cpp-httplib.dir/httplib.cpp.o
[  0%] Linking CXX static library libcpp-httplib.a
[  0%] Built target cpp-httplib
[  2%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml.c.o
[  2%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml.cpp.o
[  2%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml-alloc.c.o
[  2%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-backend.cpp.o
[  2%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-backend-meta.cpp.o
[  4%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-opt.cpp.o
[  4%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-threading.cpp.o
[  4%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml-quants.c.o
[  4%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/gguf.cpp.o
[  4%] Linking CXX shared library ../../bin/libggml-base.so
[  4%] Built target ggml-base
[  4%] Building C object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/ggml-cpu.c.o
[  6%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/ggml-cpu.cpp.o
[  6%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/repack.cpp.o
[  6%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/hbm.cpp.o
[  6%] Building C object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/quants.c.o
[  6%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/traits.cpp.o
[  9%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/amx/amx.cpp.o
[  9%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/amx/mmq.cpp.o
[  9%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/binary-ops.cpp.o
[  9%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/unary-ops.cpp.o
[  9%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/vec.cpp.o
[ 11%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/ops.cpp.o
[ 11%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/llamafile/sgemm.cpp.o
[ 11%] Building C object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/arch/x86/quants.c.o
[ 11%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/arch/x86/repack.cpp.o
[ 11%] Linking CXX shared library ../../bin/libggml-cpu.so
[ 11%] Built target ggml-cpu
[ 11%] Building CXX object ggml/src/CMakeFiles/ggml.dir/ggml-backend-dl.cpp.o
[ 11%] Building CXX object ggml/src/CMakeFiles/ggml.dir/ggml-backend-reg.cpp.o
[ 11%] Linking CXX shared library ../../bin/libggml.so
[ 11%] Built target ggml
[ 11%] Building CXX object src/CMakeFiles/llama.dir/llama.cpp.o
[ 11%] Building CXX object src/CMakeFiles/llama.dir/llama-adapter.cpp.o
[ 11%] Building CXX object src/CMakeFiles/llama.dir/llama-arch.cpp.o
[ 11%] Building CXX object src/CMakeFiles/llama.dir/llama-batch.cpp.o
[ 13%] Building CXX object src/CMakeFiles/llama.dir/llama-chat.cpp.o
[ 13%] Building CXX object src/CMakeFiles/llama.dir/llama-context.cpp.o
[ 13%] Building CXX object src/CMakeFiles/llama.dir/llama-cparams.cpp.o
[ 13%] Building CXX object src/CMakeFiles/llama.dir/llama-grammar.cpp.o
[ 13%] Building CXX object src/CMakeFiles/llama.dir/llama-graph.cpp.o
[ 13%] Building CXX object src/CMakeFiles/llama.dir/llama-hparams.cpp.o
[ 16%] Building CXX object src/CMakeFiles/llama.dir/llama-impl.cpp.o
[ 16%] Building CXX object src/CMakeFiles/llama.dir/llama-io.cpp.o
[ 16%] Building CXX object src/CMakeFiles/llama.dir/llama-kv-cache.cpp.o
[ 16%] Building CXX object src/CMakeFiles/llama.dir/llama-kv-cache-iswa.cpp.o
[ 16%] Building CXX object src/CMakeFiles/llama.dir/llama-kv-cache-dsa.cpp.o
[ 18%] Building CXX object src/CMakeFiles/llama.dir/llama-kv-cache-dsv4.cpp.o
[ 18%] Building CXX object src/CMakeFiles/llama.dir/llama-memory.cpp.o
[ 18%] Building CXX object src/CMakeFiles/llama.dir/llama-memory-hybrid.cpp.o
[ 18%] Building CXX object src/CMakeFiles/llama.dir/llama-memory-hybrid-iswa.cpp.o
[ 18%] Building CXX object src/CMakeFiles/llama.dir/llama-memory-recurrent.cpp.o
[ 20%] Building CXX object src/CMakeFiles/llama.dir/llama-mmap.cpp.o
[ 20%] Building CXX object src/CMakeFiles/llama.dir/llama-model-loader.cpp.o
[ 20%] Building CXX object src/CMakeFiles/llama.dir/llama-model-saver.cpp.o
[ 20%] Building CXX object src/CMakeFiles/llama.dir/llama-model.cpp.o
[ 20%] Building CXX object src/CMakeFiles/llama.dir/llama-quant.cpp.o
[ 20%] Building CXX object src/CMakeFiles/llama.dir/llama-sampler.cpp.o
[ 23%] Building CXX object src/CMakeFiles/llama.dir/llama-vocab.cpp.o
[ 23%] Building CXX object src/CMakeFiles/llama.dir/unicode-data.cpp.o
[ 23%] Building CXX object src/CMakeFiles/llama.dir/unicode.cpp.o
[ 23%] Building CXX object src/CMakeFiles/llama.dir/models/afmoe.cpp.o
[ 23%] Building CXX object src/CMakeFiles/llama.dir/models/apertus.cpp.o
[ 25%] Building CXX object src/CMakeFiles/llama.dir/models/arcee.cpp.o
[ 25%] Building CXX object src/CMakeFiles/llama.dir/models/arctic.cpp.o
[ 25%] Building CXX object src/CMakeFiles/llama.dir/models/arwkv7.cpp.o
[ 25%] Building CXX object src/CMakeFiles/llama.dir/models/baichuan.cpp.o
[ 25%] Building CXX object src/CMakeFiles/llama.dir/models/bailingmoe.cpp.o
[ 27%] Building CXX object src/CMakeFiles/llama.dir/models/bailingmoe2.cpp.o
[ 27%] Building CXX object src/CMakeFiles/llama.dir/models/bert.cpp.o
[ 27%] Building CXX object src/CMakeFiles/llama.dir/models/bitnet.cpp.o
[ 27%] Building CXX object src/CMakeFiles/llama.dir/models/bloom.cpp.o
[ 27%] Building CXX object src/CMakeFiles/llama.dir/models/chameleon.cpp.o
[ 27%] Building CXX object src/CMakeFiles/llama.dir/models/chatglm.cpp.o
[ 30%] Building CXX object src/CMakeFiles/llama.dir/models/codeshell.cpp.o
[ 30%] Building CXX object src/CMakeFiles/llama.dir/models/cogvlm.cpp.o
[ 30%] Building CXX object src/CMakeFiles/llama.dir/models/cohere2.cpp.o
[ 30%] Building CXX object src/CMakeFiles/llama.dir/models/cohere2moe.cpp.o
[ 30%] Building CXX object src/CMakeFiles/llama.dir/models/command-r.cpp.o
[ 32%] Building CXX object src/CMakeFiles/llama.dir/models/dbrx.cpp.o
[ 32%] Building CXX object src/CMakeFiles/llama.dir/models/deci.cpp.o
[ 32%] Building CXX object src/CMakeFiles/llama.dir/models/deepseek.cpp.o
[ 32%] Building CXX object src/CMakeFiles/llama.dir/models/deepseek2.cpp.o
[ 32%] Building CXX object src/CMakeFiles/llama.dir/models/deepseek2ocr.cpp.o
[ 32%] Building CXX object src/CMakeFiles/llama.dir/models/deepseek32.cpp.o
[ 34%] Building CXX object src/CMakeFiles/llama.dir/models/deepseek4.cpp.o
[ 34%] Building CXX object src/CMakeFiles/llama.dir/models/delta-net-base.cpp.o
[ 34%] Building CXX object src/CMakeFiles/llama.dir/models/dflash.cpp.o
[ 34%] Building CXX object src/CMakeFiles/llama.dir/models/dots1.cpp.o
[ 34%] Building CXX object src/CMakeFiles/llama.dir/models/dream.cpp.o
[ 37%] Building CXX object src/CMakeFiles/llama.dir/models/eagle3.cpp.o
[ 37%] Building CXX object src/CMakeFiles/llama.dir/models/ernie4-5-moe.cpp.o
[ 37%] Building CXX object src/CMakeFiles/llama.dir/models/ernie4-5.cpp.o
[ 37%] Building CXX object src/CMakeFiles/llama.dir/models/eurobert.cpp.o
[ 37%] Building CXX object src/CMakeFiles/llama.dir/models/exaone-moe.cpp.o
[ 39%] Building CXX object src/CMakeFiles/llama.dir/models/exaone.cpp.o
[ 39%] Building CXX object src/CMakeFiles/llama.dir/models/exaone4.cpp.o
[ 39%] Building CXX object src/CMakeFiles/llama.dir/models/falcon-h1.cpp.o
[ 39%] Building CXX object src/CMakeFiles/llama.dir/models/falcon.cpp.o
[ 39%] Building CXX object src/CMakeFiles/llama.dir/models/gemma-embedding.cpp.o
[ 39%] Building CXX object src/CMakeFiles/llama.dir/models/gemma.cpp.o
[ 41%] Building CXX object src/CMakeFiles/llama.dir/models/gemma2.cpp.o
[ 41%] Building CXX object src/CMakeFiles/llama.dir/models/gemma3.cpp.o
[ 41%] Building CXX object src/CMakeFiles/llama.dir/models/gemma3n.cpp.o
[ 41%] Building CXX object src/CMakeFiles/llama.dir/models/gemma4-assistant.cpp.o
[ 41%] Building CXX object src/CMakeFiles/llama.dir/models/gemma4.cpp.o
[ 44%] Building CXX object src/CMakeFiles/llama.dir/models/glm-dsa.cpp.o
[ 44%] Building CXX object src/CMakeFiles/llama.dir/models/glm4-moe.cpp.o
[ 44%] Building CXX object src/CMakeFiles/llama.dir/models/glm4.cpp.o
[ 44%] Building CXX object src/CMakeFiles/llama.dir/models/gpt2.cpp.o
[ 44%] Building CXX object src/CMakeFiles/llama.dir/models/gptneox.cpp.o
[ 46%] Building CXX object src/CMakeFiles/llama.dir/models/granite-hybrid.cpp.o
[ 46%] Building CXX object src/CMakeFiles/llama.dir/models/granite-moe.cpp.o
[ 46%] Building CXX object src/CMakeFiles/llama.dir/models/granite.cpp.o
[ 46%] Building CXX object src/CMakeFiles/llama.dir/models/grok.cpp.o
[ 46%] Building CXX object src/CMakeFiles/llama.dir/models/grovemoe.cpp.o
[ 46%] Building CXX object src/CMakeFiles/llama.dir/models/hunyuan-dense.cpp.o
[ 48%] Building CXX object src/CMakeFiles/llama.dir/models/hunyuan-moe.cpp.o
[ 48%] Building CXX object src/CMakeFiles/llama.dir/models/hunyuan-vl.cpp.o
[ 48%] Building CXX object src/CMakeFiles/llama.dir/models/hy-v3.cpp.o
[ 48%] Building CXX object src/CMakeFiles/llama.dir/models/internlm2.cpp.o
[ 48%] Building CXX object src/CMakeFiles/llama.dir/models/jais.cpp.o
[ 51%] Building CXX object src/CMakeFiles/llama.dir/models/jais2.cpp.o
[ 51%] Building CXX object src/CMakeFiles/llama.dir/models/jamba.cpp.o
[ 51%] Building CXX object src/CMakeFiles/llama.dir/models/jina-bert-v2.cpp.o
[ 51%] Building CXX object src/CMakeFiles/llama.dir/models/jina-bert-v3.cpp.o
[ 51%] Building CXX object src/CMakeFiles/llama.dir/models/kimi-linear.cpp.o
[ 51%] Building CXX object src/CMakeFiles/llama.dir/models/lfm2.cpp.o
[ 53%] Building CXX object src/CMakeFiles/llama.dir/models/lfm2moe.cpp.o
[ 53%] Building CXX object src/CMakeFiles/llama.dir/models/llada-moe.cpp.o
[ 53%] Building CXX object src/CMakeFiles/llama.dir/models/llada.cpp.o
[ 53%] Building CXX object src/CMakeFiles/llama.dir/models/llama-embed.cpp.o
[ 53%] Building CXX object src/CMakeFiles/llama.dir/models/llama.cpp.o
[ 55%] Building CXX object src/CMakeFiles/llama.dir/models/llama4.cpp.o
[ 55%] Building CXX object src/CMakeFiles/llama.dir/models/maincoder.cpp.o
[ 55%] Building CXX object src/CMakeFiles/llama.dir/models/mamba-base.cpp.o
[ 55%] Building CXX object src/CMakeFiles/llama.dir/models/mamba.cpp.o
[ 55%] Building CXX object src/CMakeFiles/llama.dir/models/mamba2.cpp.o
[ 58%] Building CXX object src/CMakeFiles/llama.dir/models/mellum.cpp.o
[ 58%] Building CXX object src/CMakeFiles/llama.dir/models/mimo2.cpp.o
[ 58%] Building CXX object src/CMakeFiles/llama.dir/models/minicpm.cpp.o
[ 58%] Building CXX object src/CMakeFiles/llama.dir/models/minicpm3.cpp.o
[ 58%] Building CXX object src/CMakeFiles/llama.dir/models/minimax-m2.cpp.o
[ 58%] Building CXX object src/CMakeFiles/llama.dir/models/mistral3.cpp.o
[ 60%] Building CXX object src/CMakeFiles/llama.dir/models/mistral4.cpp.o
[ 60%] Building CXX object src/CMakeFiles/llama.dir/models/modern-bert.cpp.o
[ 60%] Building CXX object src/CMakeFiles/llama.dir/models/mpt.cpp.o
[ 60%] Building CXX object src/CMakeFiles/llama.dir/models/nemotron-h-moe.cpp.o
[ 60%] Building CXX object src/CMakeFiles/llama.dir/models/nemotron-h.cpp.o
[ 62%] Building CXX object src/CMakeFiles/llama.dir/models/nemotron.cpp.o
[ 62%] Building CXX object src/CMakeFiles/llama.dir/models/neo-bert.cpp.o
[ 62%] Building CXX object src/CMakeFiles/llama.dir/models/nomic-bert-moe.cpp.o
[ 62%] Building CXX object src/CMakeFiles/llama.dir/models/nomic-bert.cpp.o
[ 62%] Building CXX object src/CMakeFiles/llama.dir/models/olmo.cpp.o
[ 62%] Building CXX object src/CMakeFiles/llama.dir/models/olmo2.cpp.o
[ 65%] Building CXX object src/CMakeFiles/llama.dir/models/olmoe.cpp.o
[ 65%] Building CXX object src/CMakeFiles/llama.dir/models/openai-moe.cpp.o
[ 65%] Building CXX object src/CMakeFiles/llama.dir/models/openelm.cpp.o
[ 65%] Building CXX object src/CMakeFiles/llama.dir/models/orion.cpp.o
[ 65%] Building CXX object src/CMakeFiles/llama.dir/models/paddleocr.cpp.o
[ 67%] Building CXX object src/CMakeFiles/llama.dir/models/pangu-embed.cpp.o
[ 67%] Building CXX object src/CMakeFiles/llama.dir/models/phi2.cpp.o
[ 67%] Building CXX object src/CMakeFiles/llama.dir/models/phi3.cpp.o
[ 67%] Building CXX object src/CMakeFiles/llama.dir/models/phimoe.cpp.o
[ 67%] Building CXX object src/CMakeFiles/llama.dir/models/plamo.cpp.o
[ 69%] Building CXX object src/CMakeFiles/llama.dir/models/plamo2.cpp.o
[ 69%] Building CXX object src/CMakeFiles/llama.dir/models/plamo3.cpp.o
[ 69%] Building CXX object src/CMakeFiles/llama.dir/models/plm.cpp.o
[ 69%] Building CXX object src/CMakeFiles/llama.dir/models/qwen.cpp.o
[ 69%] Building CXX object src/CMakeFiles/llama.dir/models/qwen2.cpp.o
[ 69%] Building CXX object src/CMakeFiles/llama.dir/models/qwen2moe.cpp.o
[ 72%] Building CXX object src/CMakeFiles/llama.dir/models/qwen2vl.cpp.o
[ 72%] Building CXX object src/CMakeFiles/llama.dir/models/qwen3.cpp.o
[ 72%] Building CXX object src/CMakeFiles/llama.dir/models/qwen35.cpp.o
[ 72%] Building CXX object src/CMakeFiles/llama.dir/models/qwen35moe.cpp.o
[ 72%] Building CXX object src/CMakeFiles/llama.dir/models/qwen3moe.cpp.o
[ 74%] Building CXX object src/CMakeFiles/llama.dir/models/qwen3next.cpp.o
[ 74%] Building CXX object src/CMakeFiles/llama.dir/models/qwen3vl.cpp.o
[ 74%] Building CXX object src/CMakeFiles/llama.dir/models/qwen3vlmoe.cpp.o
[ 74%] Building CXX object src/CMakeFiles/llama.dir/models/refact.cpp.o
[ 74%] Building CXX object src/CMakeFiles/llama.dir/models/rnd1.cpp.o
[ 76%] Building CXX object src/CMakeFiles/llama.dir/models/rwkv6-base.cpp.o
[ 76%] Building CXX object src/CMakeFiles/llama.dir/models/rwkv6.cpp.o
[ 76%] Building CXX object src/CMakeFiles/llama.dir/models/rwkv6qwen2.cpp.o
[ 76%] Building CXX object src/CMakeFiles/llama.dir/models/rwkv7-base.cpp.o
[ 76%] Building CXX object src/CMakeFiles/llama.dir/models/rwkv7.cpp.o
[ 76%] Building CXX object src/CMakeFiles/llama.dir/models/seed-oss.cpp.o
[ 79%] Building CXX object src/CMakeFiles/llama.dir/models/smallthinker.cpp.o
[ 79%] Building CXX object src/CMakeFiles/llama.dir/models/smollm3.cpp.o
[ 79%] Building CXX object src/CMakeFiles/llama.dir/models/stablelm.cpp.o
[ 79%] Building CXX object src/CMakeFiles/llama.dir/models/starcoder.cpp.o
[ 79%] Building CXX object src/CMakeFiles/llama.dir/models/starcoder2.cpp.o
[ 81%] Building CXX object src/CMakeFiles/llama.dir/models/step35.cpp.o
[ 81%] Building CXX object src/CMakeFiles/llama.dir/models/t5.cpp.o
[ 81%] Building CXX object src/CMakeFiles/llama.dir/models/t5encoder.cpp.o
[ 81%] Building CXX object src/CMakeFiles/llama.dir/models/talkie.cpp.o
[ 81%] Building CXX object src/CMakeFiles/llama.dir/models/wavtokenizer-dec.cpp.o
[ 81%] Building CXX object src/CMakeFiles/llama.dir/models/xverse.cpp.o
[ 83%] Linking CXX shared library ../bin/libllama.so
[ 83%] Built target llama
[ 86%] Building CXX object common/CMakeFiles/llama-common-base.dir/build-info.cpp.o
[ 86%] Linking CXX static library libllama-common-base.a
[ 86%] Built target llama-common-base
[ 88%] Building CXX object common/CMakeFiles/llama-common.dir/arg.cpp.o
[ 88%] Building CXX object common/CMakeFiles/llama-common.dir/chat-auto-parser-generator.cpp.o
[ 88%] Building CXX object common/CMakeFiles/llama-common.dir/chat-auto-parser-helpers.cpp.o
[ 88%] Building CXX object common/CMakeFiles/llama-common.dir/chat-diff-analyzer.cpp.o
[ 88%] Building CXX object common/CMakeFiles/llama-common.dir/chat-peg-parser.cpp.o
[ 90%] Building CXX object common/CMakeFiles/llama-common.dir/chat.cpp.o
[ 90%] Building CXX object common/CMakeFiles/llama-common.dir/common.cpp.o
[ 90%] Building CXX object common/CMakeFiles/llama-common.dir/console.cpp.o
[ 90%] Building CXX object common/CMakeFiles/llama-common.dir/debug.cpp.o
[ 90%] Building CXX object common/CMakeFiles/llama-common.dir/download.cpp.o
[ 90%] Building CXX object common/CMakeFiles/llama-common.dir/fit.cpp.o
[ 93%] Building CXX object common/CMakeFiles/llama-common.dir/hf-cache.cpp.o
[ 93%] Building CXX object common/CMakeFiles/llama-common.dir/imatrix-loader.cpp.o
[ 93%] Building CXX object common/CMakeFiles/llama-common.dir/json-schema-to-grammar.cpp.o
[ 93%] Building CXX object common/CMakeFiles/llama-common.dir/llguidance.cpp.o
[ 93%] Building CXX object common/CMakeFiles/llama-common.dir/log.cpp.o
[ 95%] Building CXX object common/CMakeFiles/llama-common.dir/ngram-cache.cpp.o
[ 95%] Building CXX object common/CMakeFiles/llama-common.dir/ngram-map.cpp.o
[ 95%] Building CXX object common/CMakeFiles/llama-common.dir/ngram-mod.cpp.o
[ 95%] Building CXX object common/CMakeFiles/llama-common.dir/peg-parser.cpp.o
[ 95%] Building CXX object common/CMakeFiles/llama-common.dir/preset.cpp.o
[ 95%] Building CXX object common/CMakeFiles/llama-common.dir/reasoning-budget.cpp.o
[ 97%] Building CXX object common/CMakeFiles/llama-common.dir/sampling.cpp.o
[ 97%] Building CXX object common/CMakeFiles/llama-common.dir/speculative.cpp.o
[ 97%] Building CXX object common/CMakeFiles/llama-common.dir/unicode.cpp.o
[ 97%] Building CXX object common/CMakeFiles/llama-common.dir/jinja/lexer.cpp.o
[ 97%] Building CXX object common/CMakeFiles/llama-common.dir/jinja/parser.cpp.o
[100%] Building CXX object common/CMakeFiles/llama-common.dir/jinja/runtime.cpp.o
[100%] Building CXX object common/CMakeFiles/llama-common.dir/jinja/value.cpp.o
[100%] Building CXX object common/CMakeFiles/llama-common.dir/jinja/string.cpp.o
[100%] Building CXX object common/CMakeFiles/llama-common.dir/jinja/caps.cpp.o
[100%] Linking CXX shared library ../bin/libllama-common.so
[100%] Built target llama-common
[100%] Building CXX object tools/quantize/CMakeFiles/llama-quantize-impl.dir/quantize.cpp.o

In [ ]:
# ========================================================
# 1. SETUP ENGINE & COMPLETE CONVERSION SYSTEM
# ========================================================
print("Setting up llama.cpp tools...")
!rm -rf llama.cpp
!git clone https://github.com/ggerganov/llama.cpp
!pip install gguf transformers sentencepiece numpy tokenizers peft accelerate safetensors

print("\nExtracting uploaded adapters...")
!unzip -o medical_adapters.zip

# ========================================================
# 2. CREATE A SUBPROCESS SCRIPT WITH TENSORFLOW MASKED OUT
# ========================================================
with open("merge_models.py", "w") as f:
    f.write('''
import sys
# Mask out tensorflow to completely bypass the broken protobuf import path
sys.modules['tensorflow'] = None

import torch
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer
import os

model_id = "Qwen/Qwen2.5-1.5B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_id)

def merge_and_save(adapter_path, output_dir):
    print(f"Executing deep tensor fusion for {adapter_path}...")
    base = AutoModelForCausalLM.from_pretrained(
        model_id,
        torch_dtype=torch.float16,
        device_map="cpu"
    )
    model = PeftModel.from_pretrained(base, adapter_path)
    merged_model = model.merge_and_unload()

    merged_model.save_pretrained(output_dir)
    tokenizer.save_pretrained(output_dir)
    print(f"Successfully compiled integrated model structure to {output_dir}\\n")

merge_and_save("./medical_lora_adapter", "./merged_lora")
merge_and_save("./medical_mtlora_adapter", "./merged_mtlora")
''')

print("\nRunning clean sub-process model fusion...")
!python merge_models.py

# ========================================================
# 3. CONVERT COMPLETED HF DIRECTORIES TO BASE GGUF
# ========================================================
print("\nConverting directories to GGUF format...")
!python llama.cpp/convert_hf_to_gguf.py ./merged_lora --outfile ./lora_fp16.gguf --outtype f16
!python llama.cpp/convert_hf_to_gguf.py ./merged_mtlora --outfile ./mtlora_fp16.gguf --outtype f16

# ========================================================
# 4. EXPORT TO 4-BIT QUANTIZATION
# ========================================================
print("\nQuantizing models to 4-bit (Q4_K_M) for Raspberry Pi...")
# Ensure quantize binary is built if it isn't already
!cd llama.cpp && cmake . -B build && cmake --build build --config Release
!./llama.cpp/build/bin/llama-quantize ./lora_fp16.gguf ./medical_lora_q4.gguf Q4_K_M
!./llama.cpp/build/bin/llama-quantize ./mtlora_fp16.gguf ./medical_mtlora_q4.gguf Q4_K_M

# Verify files exist before running the download hook
import os
if os.path.exists('medical_lora_q4.gguf') and os.path.exists('medical_mtlora_q4.gguf'):
    print("\nSuccess! Both models are successfully built into Q4_K_M GGUF format.")
    print("Initiating browser file downloads...")
    from google.colab import files
    files.download('medical_lora_q4.gguf')
    files.download('medical_mtlora_q4.gguf')
else:
    print("\n[ERROR]: GGUF files were not created. Check terminal output log traces above.")

Setting up llama.cpp tools...
Cloning into 'llama.cpp'...
remote: Enumerating objects: 103910, done.
remote: Counting objects: 100% (170/170), done.
remote: Compressing objects: 100% (129/129), done.
remote: Total 103910 (delta 87), reused 41 (delta 41), pack-reused 103740 (from 3)
Receiving objects: 100% (103910/103910), 409.67 MiB | 29.38 MiB/s, done.
Resolving deltas: 100% (72628/72628), done.
Requirement already satisfied: gguf in /usr/local/lib/python3.12/dist-packages (0.19.0)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.6)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (0.2.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (1.26.4)
Requirement already satisfied: tokenizers in /usr/local/lib/python3.12/dist-packages (0.22.2)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.19.1)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.14.0)
Requirement already satisfied: safetensors in /usr/local/lib/python3.12/dist-packages (0.8.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from gguf) (6.0.3)
Requirement already satisfied: requests>=2.25 in /usr/local/lib/python3.12/dist-packages (from gguf) (2.32.4)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from gguf) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.29.4)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.36.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft) (5.9.5)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from peft) (2.11.0+cu128)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.5.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.25->gguf) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.25->gguf) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.25->gguf) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.25->gguf) (2026.6.17)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.13.0->peft) (1.5.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.13.0->peft) (3.0.3)

Extracting uploaded adapters...
Archive:  medical_adapters.zip
  inflating: medical_lora_adapter/README.md
  inflating: medical_lora_adapter/adapter_model.safetensors
  inflating: medical_lora_adapter/adapter_config.json
  inflating: medical_mtlora_adapter/README.md
  inflating: medical_mtlora_adapter/adapter_model.safetensors
  inflating: medical_mtlora_adapter/adapter_config.json

Running clean sub-process model fusion...
Failed to load /usr/local/lib/python3.12/dist-packages/torchao/_C_cutlass_90a.abi3.so: Could not load this library: /usr/local/lib/python3.12/dist-packages/torchao/_C_cutlass_90a.abi3.so
Failed to load /usr/local/lib/python3.12/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so: Could not load this library: /usr/local/lib/python3.12/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so
tokenizer_config.json: 7.30kB [00:00, 30.5MB/s]
vocab.json: 2.78MB [00:00, 62.7MB/s]
merges.txt: 1.67MB [00:00, 101MB/s]
tokenizer.json: 7.03MB [00:00, 170MB/s]
Executing deep tensor fusion for ./medical_lora_adapter...
config.json: 100% 660/660 [00:00<00:00, 3.63MB/s]
`torch_dtype` is deprecated! Use `dtype` instead!
model.safetensors: 100% 3.09G/3.09G [00:50<00:00, 61.6MB/s]
generation_config.json: 100% 242/242 [00:00<00:00, 1.71MB/s]
Successfully compiled integrated model structure to ./merged_lora

Executing deep tensor fusion for ./medical_mtlora_adapter...
/usr/local/lib/python3.12/dist-packages/peft/peft_model.py:622: UserWarning: Found missing adapter keys while loading the checkpoint: ['base_model.model.model.layers.0.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.0.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.1.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.1.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.2.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.2.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.3.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.3.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.4.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.4.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.5.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.5.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.6.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.6.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.7.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.7.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.8.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.8.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.9.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.9.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.10.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.10.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.11.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.11.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.12.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.12.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.13.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.13.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.14.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.14.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.15.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.15.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.16.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.16.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.17.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.17.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.18.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.18.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.19.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.19.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.20.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.20.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.21.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.21.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.22.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.22.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.23.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.23.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.24.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.24.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.25.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.25.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.26.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.26.self_attn.q_proj.lora_B.default.weight', 'base_model.model.model.layers.27.self_attn.q_proj.lora_A.default.weight', 'base_model.model.model.layers.27.self_attn.q_proj.lora_B.default.weight'].
  warnings.warn(warn_message)
Successfully compiled integrated model structure to ./merged_mtlora


Converting directories to GGUF format...
INFO:hf-to-gguf:Loading model: merged_lora
INFO:hf-to-gguf:Model architecture: Qwen2ForCausalLM
INFO:hf-to-gguf:gguf: indexing model part 'model.safetensors'
INFO:gguf.gguf_writer:gguf: This GGUF file is for Little Endian only
INFO:hf-to-gguf:Exporting model...
INFO:hf-to-gguf:token_embd.weight,         torch.float16 --> F16, shape = {1536, 151936}
INFO:hf-to-gguf:blk.0.attn_norm.weight,    torch.float16 --> F32, shape = {1536}
INFO:hf-to-gguf:blk.0.ffn_down.weight,     torch.float16 --> F16, shape = {8960, 1536}
INFO:hf-to-gguf:blk.0.ffn_gate.weight,     torch.float16 --> F16, shape = {1536, 8960}
INFO:hf-to-gguf:blk.0.ffn_up.weight,       torch.float16 --> F16, shape = {1536, 8960}
INFO:hf-to-gguf:blk.0.ffn_norm.weight,     torch.float16 --> F32, shape = {1536}
INFO:hf-to-gguf:blk.0.attn_k.bias,         torch.float16 --> F32, shape = {256}
INFO:hf-to-gguf:blk.0.attn_k.weight,       torch.float16 --> F16, shape = {1536, 256}
INFO:hf-to-gguf:blk.0.attn_output.weight,  torch.float16 --> F16, shape = {1536, 1536}
INFO:hf-to-gguf:blk.0.attn_q.bias,         torch.float16 --> F32, shape = {1536}
INFO:hf-to-gguf:blk.0.attn_q.weight,       torch.float16 --> F16, shape = {1536, 1536}
INFO:hf-to-gguf:blk.0.attn_v.bias,         torch.float16 --> F32, shape = {256}
INFO:hf-to-gguf:blk.0.attn_v.weight,       torch.float16 --> F16, shape = {1536, 256}
INFO:hf-to-gguf:blk.1.attn_norm.weight,    torch.float16 --> F32, shape = {1536}
INFO:hf-to-gguf:blk.1.ffn_down.weight,     torch.float16 --> F16, shape = {8960, 1536}
INFO:hf-to-gguf:blk.1.ffn_gate.weight,     torch.float16 --> F16, shape = {1536, 8960}
INFO:hf-to-gguf:blk.1.ffn_up.weight,       torch.float16 --> F16, shape = {1536, 8960}
INFO:hf-to-gguf:blk.1.ffn_norm.weight,     torch.float16 --> F32, shape = {1536}
INFO:hf-to-gguf:blk.1.attn_k.bias,         torch.float16 --> F32, shape = {256}
INFO:hf-to-gguf:blk.1.attn_k.weight,       torch.float16 --> F16, shape = {1536, 256}
INFO:hf-to-gguf:blk.1.attn_output.weight,  torch.float16 --> F16, shape = {1536, 1536}
INFO:hf-to-gguf:blk.1.attn_q.bias,         torch.float16 --> F32, shape = {1536}
INFO:hf-to-gguf:blk.1.attn_q.weight,       torch.float16 --> F16, shape = {1536, 1536}
INFO:hf-to-gguf:blk.1.attn_v.bias,         torch.float16 --> F32, shape = {256}
INFO:hf-to-gguf:blk.1.attn_v.weight,       torch.float16 --> F16, shape = {1536, 256}
INFO:hf-to-gguf:blk.10.attn_norm.weight,   torch.float16 --> F32, shape = {1536}
INFO:hf-to-gguf:blk.10.ffn_down.weight,    torch.float16 --> F16, shape = {8960, 1536}
INFO:hf-to-gguf:blk.10.ffn_gate.weight,    torch.float16 --> F16, shape = {1536, 8960}
INFO:hf-to-gguf:blk.10.ffn_up.weight,      torch.float16 --> F16, shape = {1536, 8960}
INFO:hf-to-gguf:blk.10.ffn_norm.weight,    torch.float16 --> F32, shape = {1536}
INFO:hf-to-gguf:blk.10.attn_k.bias,        torch.float16 --> F32, shape = {256}
INFO:hf-to-gguf:blk.10.attn_k.weight,      torch.float16 --> F16, shape = {1536, 256}
INFO:hf-to-gguf:blk.10.attn_output.weight, torch.float16 --> F16, shape = {1536, 1536}
INFO:hf-to-gguf:blk.10.attn_q.bias,        torch.float16 --> F32, shape = {1536}
INFO:hf-to-gguf:blk.10.attn_q.weight,      torch.float16 --> F16, shape = {1536, 1536}
INFO:hf-to-gguf:blk.10.attn_v.bias,        torch.float16 --> F32, shape = {256}
INFO:hf-to-gguf:blk.10.attn_v.weight,      torch.float16 --> F16, shape = {1536, 256}
INFO:hf-to-gguf:blk.11.attn_norm.weight,   torch.float16 --> F32, shape = {1536}
INFO:hf-to-gguf:blk.11.ffn_down.weight,    torch.float16 --> F16, shape = {8960, 1536}
INFO:hf-to-gguf:blk.11.ffn_gate.weight,    torch.float16 --> F16, shape = {1536, 8960}
INFO:hf-to-gguf:blk.11.ffn_up.weight,      torch.float16 --> F16, shape = {1536, 8960}
INFO:hf-to-gguf:blk.11.ffn_norm.weight,    torch.float16 --> F32, shape = {1536}
INFO:hf-to-gguf:blk.11.attn_k.bias,        torch.float16 --> F32, shape = {256}
INFO:hf-to-gguf:blk.11.attn_k.weight,      torch.float16 --> F16, shape = {1536, 256}
INFO:hf-to-gguf:blk.11.attn_output.weight, torch.float16 --> F16, shape = {1536, 1536}
INFO:hf-to-gguf:blk.11.attn_q.bias,        torch.float16 --> F32, shape = {1536}
INFO:hf-to-gguf:blk.11.attn_q.weight,      torch.float16 --> F16, shape = {1536, 1536}
INFO:hf-to-gguf:blk.11.attn_v.bias,        torch.float16 --> F32, shape = {256}
INFO:hf-to-gguf:blk.11.attn_v.weight,      torch.float16 --> F16, shape = {1536, 256}
INFO:hf-to-gguf:blk.12.attn_norm.weight,   torch.float16 --> F32, shape = {1536}
INFO:hf-to-gguf:blk.12.ffn_down.weight,    torch.float16 --> F16, shape = {8960, 1536}
INFO:hf-to-gguf:blk.12.ffn_gate.weight,    torch.float16 --> F16, shape = {1536, 8960}
INFO:hf-to-gguf:blk.12.ffn_up.weight,      torch.float16 --> F16, shape = {1536, 8960}
INFO:hf-to-gguf:blk.12.ffn_norm.weight,    torch.float16 --> F32, shape = {1536}
INFO:hf-to-gguf:blk.12.attn_k.bias,        torch.float16 --> F32, shape = {256}
INFO:hf-to-gguf:blk.12.attn_k.weight,      torch.float16 --> F16, shape = {1536, 256}
INFO:hf-to-gguf:blk.12.attn_output.weight, torch.float16 --> F16, shape = {1536, 1536}
INFO:hf-to-gguf:blk.12.attn_q.bias,        torch.float16 --> F32, shape = {1536}
INFO:hf-to-gguf:blk.12.attn_q.weight,      torch.float16 --> F16, shape = {1536, 1536}
INFO:hf-to-gguf:blk.12.attn_v.bias,        torch.float16 --> F32, shape = {256}
INFO:hf-to-gguf:blk.12.attn_v.weight,      torch.float16 --> F16, shape = {1536, 256}
INFO:hf-to-gguf:blk.13.attn_norm.weight,   torch.float16 --> F32, shape = {1536}
INFO:hf-to-gguf:blk.13.ffn_down.weight,    torch.float16 --> F16, shape = {8960, 1536}
INFO:hf-to-gguf:blk.13.ffn_gate.weight,    torch.float16 --> F16, shape = {1536, 8960}
INFO:hf-to-gguf:blk.13.ffn_up.weight,      torch.float16 --> F16, shape = {1536, 8960}
INFO:hf-to-gguf:blk.13.ffn_norm.weight,    torch.float16 --> F32, shape = {1536}
INFO:hf-to-gguf:blk.13.attn_k.bias,        torch.float16 --> F32, shape = {256}

In [ ]:
# Launch the llama.cpp web server on a fresh port (8090)
!./llama.cpp/build/bin/llama-server -m ./medical_lora_q4.gguf -c 2048 --port 8090

/bin/bash: line 1: ./llama.cpp/build/bin/llama-server: No such file or directory

In [ ]:
from google.colab.output import eval_js
link = eval_js('google.colab.kernel.proxyPort(8090)')
print("-" * 50)
print(f"CLICK HERE TO CHAT: {link}")
print("-" * 50)